name: flutter_bloc_post
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_bloc: ^3.2.0
  cloud_firestore: ^4.4.5
  firebase_storage: ^11.0.16
  equatable: ^2.0.5
  meta: ^1.8.0
  intl: ^0.18.0
  image_picker: ^0.8.7
  firebase_core: ^2.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

